default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username:
  password:
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: friend_ranch_development

test:
  <<: *default
  database: friend_ranch_test
